micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
#    schema-generate: CREATE_DROP
    dialect: H2

    #JPA
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true


# Para usar postgres
#datasources:
#  default:
#    url: ${DB_URL:`jdbc:postgresql://localhost:5432/cdc`}
#    driverClassName: org.postgresql.Driver
#    username: ${DB_USER:postgres}
#    password: ${DB_PASSWORD:postgres}
#    dialect: POSTGRES